//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBosCRM.Models
{
    using System;
    
    public partial class ApplicationUserInfos
    {
        public System.Guid ApplicationUserID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime DoB { get; set; }
        public Nullable<int> TotalPermissionAssigned { get; set; }
    }
}
