//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBosCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EbosEntities : DbContext
    {
        public EbosEntities()
            : base("name=EbosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationUserPermissionGroup> ApplicationUserPermissionGroups { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<CustomerCall> CustomerCalls { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<PermissionGroup> PermissionGroups { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
    
        public virtual ObjectResult<ApplicationUserInfos> GetApplicationUserInfos(Nullable<System.Guid> applicationUserID)
        {
            var applicationUserIDParameter = applicationUserID.HasValue ?
                new ObjectParameter("ApplicationUserID", applicationUserID) :
                new ObjectParameter("ApplicationUserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApplicationUserInfos>("GetApplicationUserInfos", applicationUserIDParameter);
        }
    }
}
