//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBosCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public System.Guid PermissionID { get; set; }
        public System.Guid PermissionGroupID { get; set; }
        public string PermissionName { get; set; }
        public string PermissionDescription { get; set; }
    
        public virtual PermissionGroup PermissionGroup { get; set; }
    }
}
